@URL = http://localhost:5106

GET {{URL}}/weatherforecast/
Accept: application/json

###
GET {{URL}}/api/product
accept: application/json
###
GET {{URL}}/api/product/102
accept: application/json
###
POST {{URL}}/api/product
content-type: application/json
{
    "productName": "aaaaaaaaaaaa",
    "brandId": 1,
    "categoryId": 1,
    "description": "bbbbbbbbbbbbbbbbb",
    "basePrice": 23232323.00
}
###
PUT {{URL}}/api/product/102
content-type: application/json
{
    "productName": "11111123111111111",
    "brandId": 1,
    "categoryId": 1,
    "description": "123",
    "basePrice": 23232323.00
}

###
DELETE {{URL}}/api/product/101
Accept: application/json

###
GET {{URL}}/api/product/searchAsync?keyword=100
Accept: application/json

###
POST {{URL}}/api/Auth/register
content-type: application/json
{
    "Email": "minh@123",
    "Password": "123456"
}
###
POST {{URL}}/api/Auth/login
content-type: application/json
{
    "Email": "minh@123",
    "Password": "123456"
}
###
GET {{URL}}/api/User?keyword=inh
content-type: application/json

###
POST {{URL}}/api/User
content-type: application/json
{
    "Email" : "quanminh", 
    "Password" : "123466",
    "Roles" : [
        "Stringer",
        "Customer"
    ]
}